# Chap.4 numpy套件(numeric python)
## 為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [1]:
a_list=[1,2,3,4,5] #a_list存放5個數字
print(a_list*3)    #寫出5個數字3次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [1]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np   #將np宣告成numpy
a=np.array([1,2,3,4,5]) #a等於np內的5個數字
print(a*3)  #寫出5個數字的3倍各是多少

[ 3  6  9 12 15]


In [6]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int32
1


In [12]:
import numpy as np
z=np.zeros(6)  #z有6個0
print(z)
print(np.empty((2,3,4)))#z的維度 為2次的3*4矩陣
print(np.arange(10))#寫出安排的10個數 0開始數

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [16]:
my_array=np.arange(10)
print(my_array)#寫出安排的10個數 0開始數
print(my_array[0])#寫出安排的10個數的第0位數字
print(my_array[0:5])#寫出安排的10個數的第0位到第5位數字

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


### 2維資料取值

In [20]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)#寫出安排的10個數的數字
print(my_2d_array[1,:])#寫出np.array第1排的數值:np.arange(5,10)
print(my_2d_array[:,1])#寫出每排的第一個數值
print(my_2d_array[1,1])#寫出第一排的第一個數值

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [25]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)#查詢my_array的維數
my_2d_array=my_array.reshape(2,5)#存成2*5的陣列
print(my_2d_array)
print((np.arange(0,100).reshape(10,10)))#寫出0,100個數值並且用10*10的矩陣輸出

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### numpy的空值nan

In [26]:
b=np.array([56, 8, 19, 14, np.nan])
print(b)

[56.  8. 19. 14. nan]
